### ISSUE TITLE
CI/CD checks and actions failing

### ISSUE THREAD

**Issue by paulyuk** [Azure-Samples/Azure-Functions-OpenAI-Demo#10]
The actions workflows should be updated so we build clean and stay clean.

One obvious issue is the Functions check assumes Python, and this is a .NET app

Example:
https://github.com/Azure-Samples/Azure-Functions-OpenAI-Demo/actions/runs/9756517622/job/26926988221

**Comment by eamonoreilly** [comment]
Fixed in https://github.com/Azure-Samples/Azure-Functions-OpenAI-Demo/pull/20
