### ISSUE TITLE
Link and Content error in README.md

### ISSUE THREAD

**Issue by jerryshia** [Azure-Samples/Azure-Functions-OpenAI-Demo#18]
1.
**Describe the issue:**
Missing step to download repo code.

![image](https://github.com/user-attachments/assets/d9ff6eab-b00b-4b7d-be1b-3ec415eafbf7)

**Suggestion:**
Add step before step 1:

1.Run the following command to download the project code:
```
azd init -t john0isaac/simple-flask-app-terraform
```

2.
**Describe the issue:**
In the [README.md](https://github.com/Azure-Samples/Azure-Functions-OpenAI-Demo?tab=readme-ov-file#running-locally-currently-untestedunsupported), when click `Docker`, the link leads to a 404 page.:

![image](https://github.com/user-attachments/assets/d82a6dbe-d47e-4ed1-bb6f-711df6a456d1)

**Expected behavior:**
Clicking on `Docker` can successfully open the page.

@hemarina and @BigMorty  for notification.

**Comment by eamonoreilly** [comment]
Fixed link to open docker site and updated instructions to use azd init -t to get the content locally and initialize. https://github.com/Azure-Samples/Azure-Functions-OpenAI-Demo/pull/23
