### ISSUE TITLE
Fail to run `func start`

### ISSUE THREAD

**Issue by jerryshia** [Azure-Samples/Azure-Functions-OpenAI-Demo#19]
**Describe the issue:**
When running `func start` , the following error occurs:

![image](https://github.com/user-attachments/assets/9104df32-cd0d-4127-a73d-ce5db1bec366)

If cd into `app/backend` and running `fun start`, the operation is successful, but` http://127.0.0.1:5000/` cannot be accessed.
![image](https://github.com/user-attachments/assets/17cf865f-3a2a-496d-914b-4e526b4fd6ef)

![image](https://github.com/user-attachments/assets/8676817b-ff69-4907-a69e-c025aa4fa7a3)

**Repro Steps:**

1. Run `azd init -t Azure-Functions-OpenAI-Demo`.
2. Run `azd auth login`.
3. Run `set-executionpolicy remotesigned`
4. Run `azd up`.
5. Create a new `app/backend/local.settings.json` file to store Azure resource configuration using values in the .azure/[environment name]
6. Disable VNET private endpoints in resource group .
7. Start Azurite using VS Code extension
8. Run `func start`.

**Environment:**

- azd version 1.10.2 (commit 84ea22048b9a1c167bc4ae2095cc7f91798ef11e)
- OS: Windows

**Expected behavior:**
Run `func start` successful  and `http://127.0.0.1:5000/ `can be accessed successfully.

@hemarina and @BigMorty  for notification.

**Comment by eamonoreilly** [comment]
Updated instructions for running locally #25

**Comment by jerryshia** [comment]
This issue has been fixed. Close it.
